In [1]:
import numpy
import pandas
import sklearn
import fastapi
print("Environment Ready")

Environment Ready


In [2]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("soil_quality_dataset.csv")

df.head()

,Soil_Type,pH,EC,Organic_Carbon,Nitrogen,Phosphorus,Potassium,Moisture,Temperature,Soil_Quality
0,Clay,4.91,1.33,0.96,84,74,531,15.66,29.19,Poor
1,Sandy,8.63,1.53,0.80,297,65,432,14.14,12.02,Good
2,Clay,5.12,2.19,0.89,90,30,528,36.62,17.59,Poor
3,Clay,8.78,2.46,1.09,406,75,68,42.46,34.24,Good
4,Sandy,6.51,1.14,0.54,196,87,78,26.04,15.01,Moderate


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Soil_Type       1500 non-null   object 
 1   pH              1500 non-null   float64
 2   EC              1500 non-null   float64
 3   Organic_Carbon  1500 non-null   float64
 4   Nitrogen        1500 non-null   int64  
 5   Phosphorus      1500 non-null   int64  
 6   Potassium       1500 non-null   int64  
 7   Moisture        1500 non-null   float64
 8   Temperature     1500 non-null   float64
 9   Soil_Quality    1500 non-null   object 
dtypes: float64(5), int64(3), object(2)
memory usage: 117.3+ KB


In [6]:
df.isnull().sum()

Soil_Type         0
pH                0
EC                0
Organic_Carbon    0
Nitrogen          0
Phosphorus        0
Potassium         0
Moisture          0
Temperature       0
Soil_Quality      0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Soil_Type"] = le.fit_transform(df["Soil_Type"])

In [8]:
print(dict(zip(le.classes_, le.transform(le.classes_))))

{'Clay': np.int64(0), 'Loamy': np.int64(1), 'Sandy': np.int64(2)}


In [9]:
from sklearn.preprocessing import LabelEncoder

le_quality = LabelEncoder()

df["Soil_Quality"] = le_quality.fit_transform(df["Soil_Quality"])

In [12]:
X = df.drop(["Soil_Type","Soil_Quality"], axis=1)
y = df["Soil_Type"]

# X → input features
# y → output label

In [13]:
print(X.shape)
print(y.shape)

(1500, 8)
(1500,)


In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Step 4 — Train/Test Split (Next Step)
# 80% → training data
# 20% → testing data
# After defining X and y, the next step is splitting data:  

# Load Dataset
#       ↓
# Check Missing Values
#       ↓
# Encode Soil_Type
#       ↓
# Define X (input)
# Define y (output)
#       ↓
# Train/Test Split
#       ↓
# Train Model 

In [18]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [19]:
from sklearn.metrics import accuracy_score

pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.34


In [20]:
df["Soil_Type"].value_counts()

Soil_Type
2    520
1    492
0    488
Name: count, dtype: int64

In [21]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    random_state=42
)

model.fit(X_train, y_train)

,n_estimators,300
,criterion,'gini'
,max_depth,15
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [24]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=400,
    max_depth=20,
    random_state=42
)

model.fit(X_train, y_train)

,n_estimators,400
,criterion,'gini'
,max_depth,20
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [25]:
from sklearn.metrics import accuracy_score

pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.33


In [26]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [27]:
from sklearn.metrics import accuracy_score

pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.33


In [29]:
from sklearn.preprocessing import LabelEncoder

le_type = LabelEncoder()
le_quality = LabelEncoder()

df["Soil_Type"] = le_type.fit_transform(df["Soil_Type"])
df["Soil_Quality"] = le_quality.fit_transform(df["Soil_Quality"])

In [30]:
X = df.drop("Soil_Type", axis=1)
y = df["Soil_Type"]

In [31]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

In [34]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=600,
    max_depth=25,
    min_samples_split=5,
    random_state=42
)

model.fit(X_train, y_train)

,n_estimators,600
,criterion,'gini'
,max_depth,25
,min_samples_split,5
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [36]:
X = df.drop("Soil_Quality", axis=1)
y = df["Soil_Quality"]

In [37]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(n_estimators=500, random_state=42)
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 1.0


In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [40]:
model.fit(X_train, y_train)

,n_estimators,500
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [41]:
print(X_train.shape)
print(X_test.shape)

(1200, 9)
(300, 9)


In [42]:
print(X_train.shape)
print(X_test.shape)

(1200, 9)
(300, 9)


In [43]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, pred))

[[88  0  0  0]
 [ 0 78  0  0]
 [ 0  0 41  0]
 [ 0  0  0 93]]


In [44]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, cv=5)

print(scores)
print("Average:", scores.mean())

[1.         0.99666667 1.         1.         1.        ]
Average: 0.9993333333333332


In [45]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, cv=5)

print(scores)
print("Average:", scores.mean())

[1.         0.99666667 1.         1.         1.        ]
Average: 0.9993333333333332


In [46]:
print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 1.0


In [47]:
import joblib

joblib.dump(model, "soil_model.pkl")
joblib.dump(le, "soil_encoder.pkl")

['soil_encoder.pkl']

In [131]:
import pandas as pd

sample = pd.DataFrame([[6.5,0.45,0.75,80,50,100,30,25,1]], columns=X.columns)

soil_pred = model.predict(sample)

print("Predicted Soil:", le.inverse_transform(soil_pred))



Predicted Soil: ['Loamy']
